# Generated by Django 3.2.4 on 2023-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на видео')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
