# Generated by Django 3.2.4 on 2023-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликован"
            ),
        ),
    ]
