# Generated by Django 3.2.4 on 2023-10-29 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст обращения")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "обращение",
                "verbose_name_plural": "обращения",
            },
        ),
        migrations.CreateModel(
            name="TicketAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="ответ на обращение")),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.ticket",
                        verbose_name="обращение",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ на обращение",
                "verbose_name_plural": "ответы на обращения",
            },
        ),
    ]
